version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: festival-mysql
    ports:
      - "3307:3306"     #충돌난다면 - "3307:3306" # 3306 대신 3307로 변경 이런식으로 변경
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always

